import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className= {styles.header}>
            <h1 className={styles.logo}>Cookie Stand Admin </h1>
      </header>
      <main className={styles.main} >
        <div >
          <h2 className={styles.description}>
            Create Cookie Stand
          </h2>
          <form className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 bg-green-500">
            <div className="mb-4">

              <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="username">
                Minimum Customer per Hour
              </label>
              <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="username" type="text" placeholder="Minimum Customer per Hour">
              </input>

              <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="username">
                Maximum Customer per Hour
              </label>
              <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="username" type="text" placeholder="Maximum Customer per Hour">
              </input>

              <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="username">
                Average Customer per Sale
              </label>
              <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="username" type="text" placeholder="Average Customer per Sale">
              </input>
            </div>

            <button className="bg-white hover:bg-green-300 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="button">
              Sign In
            </button>
          </form>

        </div>
        <p className={styles.description}>
          report table coming soon
        </p>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          @2021{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}